### ISSUE TITLE
Implementasi FOR LOOP tanpa INISIALISASI, KONDISI, dan UPDATE

### ISSUE THREAD

**Issue by haizk** [stackofsugar/TeachingAssistant-KP2021#6]
Perkenalkan, nama saya Hezkiel Bram Setiawan dengan NIM M0521030
Di sini saya akan memberikan contoh implementasi FOR LOOP tanpa INISIALISASI, KONDISI, dan UPDATE

Source codenya
https://snipsave.com/user/haizkhaizk/snippet/PbGlGPIt7I1qYFdNTy/

```c
#include <stdio.h>
#include <stdlib.h>
//SEBENARNYA BISA SAJA TANPA MENGGUNAKAN <time.h>, TETAPI HASIL AKHIR AKAN LANGSUNG DIKETAHUI SETELAH MEMASUKKAN NILAI
#include <time.h>

//DUEL BALAP KELINCI 100M
int main()
{
    printf("Balap kelinci 100 meter\n\n");
    srand(time(0));
    
    //PENDATAAN
    int a=0, b=0, chance1, chance2, cape1=0, cape2=0;
    char nama1[100], nama2[100];
    char alias1, alias2;
    int kec1, kec2;
    printf("Nama kelinci pertama: ");
    scanf("%s", nama1);
    printf("Inisial kelinci pertama: ");
    scanf(" %c", &alias1);
    printf("Jauh lompatan kelinci pertama: ");
    scanf("%d", &kec1);
    printf("Nama kelinci kedua: ");
    scanf("%s", nama2);
    printf("Inisial kelinci kedua: ");
    scanf(" %c", &alias2);
    printf("Jauh lompatan kelinci kedua: ");
    scanf("%d", &kec2);

    //BALAPAN DIMULAI
    printf("\nLINKO STARTO!\n\n%c\n%c\n", alias1, alias2);
    
    /* KELINCI DENGAN NILAI LOMPATAN YANG LEBIH BESAR MEMPUNYAI KEMUNGKINAN YANG LEBIH BESAR
    UNTUK BERHENTI DI JALAN DARIPADA KELINCI DENGAN NILAI LOMPATAN YANG LEBIH KECIL
    APABILA NILAI LOMPATAN SAMA, KEMUNGKINAN KELINCI UNTUK BERHENTI DI JALAN ADALAH SAMA */
    if(kec1>kec2){
        chance1=60;
        chance2=75;
    } else if(kec1<kec2){
        chance1=75;
        chance2=60;
    } else{
        chance1=chance2=50;
    }
    
    //PENGGUNAAN FOR LOOP TANPA INISIALISASI, KONDISI, DAN UPDATE
    for(;;){
    
        //HAL-HAL TAMPILAN
        if(rand()%100 >= chance1 && a>kec1){
            a-=kec1;
            if(cape1==0){
                printf("%s capek, mau istirahat dulu\n", nama1);
                cape1++;
            } else if(cape1==1){
                printf("%s capek banget dah, minum dulu kali ya\n", nama1);
                cape1++;
            } else printf("tau deh %s mager banget\n", nama1);
        } else cape1=0;
        if(rand()%100 >= chance2 && b>kec2){
            b-=kec2;
            if(cape2==0){
                printf("%s capek, mau istirahat dulu\n", nama2);
                cape2++;
            } else if(cape2==1){
                printf("%s capek banget dah, minum dulu kali ya\n", nama2);
                cape2++;
            } else printf("tau deh %s mager banget\n", nama2);
        } else cape2=0;
        for(int x=0; x<a; x++){
            printf(" ");
            if(x==a-1) printf("%c\n", alias1);
        }
        for(int x=0; x<b; x++){
            printf(" ");
            if(x==b-1) printf("%c\n", alias2);
        }
        printf("----------------------------------------------------------------------------------------------------FINISH\n");
        
        //KONDISI SELESAI (KELUAR DARI FOR LOOP)
        if(a>=100 && b<100){
            printf("\nIRI BILANG BOS\nPemenangnya adalah %s", nama1);
            break;
        } else if(b>=100 && a<100){
            printf("\nIRI BILANG BOS\nPemenangnya adalah %s", nama2);
            break;
        } else if(a>=100 && b>=100){
            printf("\nYHAHAH SERI");
            break;
        }
        
        //INCREMENT
        a+=kec1;
        b+=kec2;
    }
    return 0;
}
```

Berikut adalah contoh RUN code tersebut:
![Screenshot 2021-09-02 084743](https://user-images.githubusercontent.com/78388591/131768417-15f06f27-33d5-48f5-9eb3-f4f45d8468b4.png)
![Screenshot 2021-09-02 084821](https://user-images.githubusercontent.com/78388591/131768423-bbca498a-9960-46cc-bcbd-ce4f43198e9d.png)

Pada penjelasan 
![image](https://user-images.githubusercontent.com/78388591/131767434-cb91b920-c2a3-4d6b-b254-5a424aa6620d.png)
Tertulis bahwa FOR LOOP bisa digunakan dengan menghilangkan komponen selain INISIALISASI, tetapi setelah saya coba, saya bisa menggunakan FOR LOOP tanpa INISIALISASI, KONDISI, DAN UPDATE

Penggunaan FOR(;;) sama seperti WHILE(1), akan terus berjalan apabila tidak ada BREAK

Apabila ada tanggapan, silahkan comment
Terima kasih🙏

**Comment by haizk** [comment]
#include <stdio.h>
#include <stdlib.h>
//SEBENARNYA BISA SAJA TANPA MENGGUNAKAN <time.h>, TETAPI HASIL AKHIR AKAN LANGSUNG DIKETAHUI SETELAH MEMASUKKAN NILAI
#include <time.h>

//DUEL BALAP KELINCI 100M
int main()
{
    printf("Balap kelinci 100 meter\n\n");
    srand(time(0));
    
    //PENDATAAN
    int a=0, b=0, chance1, chance2, cape1=0, cape2=0;
    char nama1[100], nama2[100];
    char alias1, alias2;
    int kec1, kec2;
    printf("Nama kelinci pertama: ");
    scanf("%s", nama1);
    printf("Inisial kelinci pertama: ");
    scanf(" %c", &alias1);
    printf("Jauh lompatan kelinci pertama: ");
    scanf("%d", &kec1);
    printf("Nama kelinci kedua: ");
    scanf("%s", nama2);
    printf("Inisial kelinci kedua: ");
    scanf(" %c", &alias2);
    printf("Jauh lompatan kelinci kedua: ");
    scanf("%d", &kec2);

    //BALAPAN DIMULAI
    printf("\nLINKO STARTO!\n\n%c\n%c\n", alias1, alias2);
    
    /* KELINCI DENGAN NILAI LOMPATAN YANG LEBIH BESAR MEMPUNYAI KEMUNGKINAN YANG LEBIH BESAR
    UNTUK BERHENTI DI JALAN DARIPADA KELINCI DENGAN NILAI LOMPATAN YANG LEBIH KECIL
    APABILA NILAI LOMPATAN SAMA, KEMUNGKINAN KELINCI UNTUK BERHENTI DI JALAN ADALAH SAMA */
    if(kec1>kec2){
        chance1=60;
        chance2=75;
    } else if(kec1<kec2){
        chance1=75;
        chance2=60;
    } else{
        chance1=chance2=50;
    }
    
    //PENGGUNAAN FOR LOOP TANPA INISIALISASI, KONDISI, DAN UPDATE
    for(;;){
    
        //HAL-HAL TAMPILAN
        if(rand()%100 >= chance1 && a>kec1){
            a-=kec1;
            if(cape1==0){
                printf("%s capek, mau istirahat dulu\n", nama1);
                cape1++;
            } else if(cape1==1){
                printf("%s capek banget dah, minum dulu kali ya\n", nama1);
                cape1++;
            } else printf("tau deh %s mager banget\n", nama1);
        } else cape1=0;
        if(rand()%100 >= chance2 && b>kec2){
            b-=kec2;
            if(cape2==0){
                printf("%s capek, mau istirahat dulu\n", nama2);
                cape2++;
            } else if(cape2==1){
                printf("%s capek banget dah, minum dulu kali ya\n", nama2);
                cape2++;
            } else printf("tau deh %s mager banget\n", nama2);
        } else cape2=0;
        for(int x=0; x<a; x++){
            printf(" ");
            if(x==a-1) printf("%c\n", alias1);
        }
        for(int x=0; x<b; x++){
            printf(" ");
            if(x==b-1) printf("%c\n", alias2);
        }
        printf("----------------------------------------------------------------------------------------------------FINISH\n");
        
        //KONDISI SELESAI (KELUAR DARI FOR LOOP)
        if(a>=100 && b<100){
            printf("\nIRI BILANG BOS\nPemenangnya adalah %s", nama1);
            break;
        } else if(b>=100 && a<100){
            printf("\nIRI BILANG BOS\nPemenangnya adalah %s", nama2);
            break;
        } else if(a>=100 && b>=100){
            printf("\nYHAHAH SERI");
            break;
        }
        
        //INCREMENT
        a+=kec1;
        b+=kec2;
    }
    return 0;
}

**Comment by haizk** [comment]
Terima kasih mas udah diedit😅🤣tadi dicoba buat masukin codenya gabisa

**Comment by stackofsugar** [comment]
Hai, @haizk! Terimakasih sudah memberikan contoh yang sangat baik mengenai behavior `for` loop. Kami sebagai mantainer repo ini sangat mengapresiasi tambahan materi yang sudah kamu berikan untuk repository ini. Selamat juga atas pembukaan issue pertamamu di GitHub!

Kami sudah memahami dan menangkap poinmu mengenai *ommitance* dari ketiga initial value dari `for` loop, yaitu init, condition, dan update. Kamu telah memberikan contoh yang sangat baik mengenai teori tersebut dalam bentuk **game kelinci** di atas. Kami akan menyisipkan materi mengenai penggunaan `for` loop sesuai skema di atas (`for ( ; ; ) {...}`), namun kami akan menggunakan contoh yang lebih mudah, dikarenakan **game kelinci** yang kamu buat mungkin akan terlihat cukup membingungkan untuk peserta praktikum lain dalam menjelaskan teori yang cukup simpel. Kami juga akan memperbarui *contributing guideline* kami.

Sebagai tambahan, kami melihat bahwa kamu membuat program contoh di atas dengan kreativitas yang tinggi. Kami menyarankan untuk menggunakan kode (atau ide) di atas sebagai submisimu dalam tugas responsi (dan mungkin menambahkan materi-materi yang akan diberikan lebih lanjut pada game mu), karena pada tugas responsi, kreativitas memiliki persentase cukup tinggi pada penilaian dan kami sangat mengapresiasi peserta praktikum yang membuat kode *out of the box*.

Involved mantainer tag: @michaelrk02 @Drithh @alwizzz 

> Note: Issue ini akan tetap dibuka hingga materi ditambahkan/persoalan resolved, dan selama issue masih dibuka, diskusi dapat dilakukan

**Comment by haizk** [comment]
Baik mas @stackofsugar. Terima kasih atas sarannya.

**Comment by stackofsugar** [comment]
Resolved [here](https://github.com/stackofsugar/TeachingAssistant-KP2021/blob/main/Bab3-ProgramControl/4-PerulanganBreakContinue.md#bonus--infinite-loop)
